### ISSUE TITLE
Failed to read NFPM _positions value after triggering DecreaseLiquidity and Collect events.

### ISSUE THREAD

**Issue by nikugogoi** [vulcanize/uniswap-watcher-ts#149]
Error: `error decoding storage leaf node rlp: EOF`

Steps to reproduce:

1. Follow steps in https://github.com/vulcanize/uniswap-v3-periphery/blob/watcher-ts/demo.md (Can skip Pool mint, burn and swap)

2. After `yarn position-manager:collect` error displayed in uni-info-watcher server log.

3. Can also try fetching _positions value in graphql browser playground. Open http://localhost:3003/graphql (uni-watcher server)
    ```graphql
    position(tokenId: "1", blockHash: "0xfd2fdfec1f13cf68f136cc1095111e42d4e5916f654b88ad6cba9676c0cf8c91") {
      poolId
      tokensOwed0
      tokensOwed1
    }
    ```
    
Analysis:
* Using `blockHash` before Collect event works (Can get from uni-watcher server ).
* Error comes from getStorageValue of solidity-mapper. Using solidity-mapper getStorageValue with geth RPC instead of `ipld-eth-client` works.

**Comment by nikugogoi** [comment]
Error in ipld-eth-server originates from https://github.com/vulcanize/ipld-eth-server/blob/master/pkg/eth/ipld_retriever.go#L450

**Comment by ramilexe** [comment]
PR: https://github.com/vulcanize/ipld-eth-server/pull/94

**Comment by Burmenska** [comment]
estimation is updated according to Ian's request:
 we want to fix the function even if it isn't currently called. We could test account deleting similar to how we do it here: https://github.com/vulcanize/go-ethereum/blob/v1.10.7-statediff/statediff/builder_test.go#L1318

**Comment by arijitAD** [comment]
This issue is fixed in master. Added description here https://github.com/vulcanize/ipld-eth-server/issues/99

**Comment by arijitAD** [comment]
https://github.com/vulcanize/ipld-eth-server/pull/98

**Comment by i-norden** [comment]
https://github.com/vulcanize/ipld-eth-server/issues/104

**Comment by arijitAD** [comment]
This issue is fixed by this PR https://github.com/vulcanize/ipld-eth-server/issues/104
