### ISSUE TITLE
Use ipld-eth-server RPC endpoint for eth_call

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/uniswap-watcher-ts#169]
Fix depends on https://github.com/vulcanize/ops/issues/64

**Comment by nikugogoi** [comment]
Getting errors in eth_call when using ipld-eth-server RPC endpoint
Error from ethers.js which is using the endpoint
```
reason: 'processing response error',
code: 'SERVER_ERROR',
body: '{"jsonrpc":"2.0","id":44,"error":{"code":-32000,"message":"eth_call failed without error"}}\n',
error: Error: eth_call failed without error
  code: -32000,
  data: undefined
```

Error in ipld-eth-server log
```
ERRO[2021-08-06T12:02:18+05:30] tx cid retrieval error                       
ERRO[2021-08-06T12:02:18+05:30] ChainId failed with err missing destination name tx_type in *[]eth.TxModel 
WARN[2021-08-06T12:02:18+05:30] Caller gas above allowance, capping; requested: 9223372036854775807, cap: 1000000000000
```
Notes:
* Same eth_call works for geth_server.
* Methods like getBalance and blockNumber are working for ipld-eth-server.

**Comment by ramilexe** [comment]
Probably the problem with chain config. Please take a look: https://github.com/vulcanize/ipld-eth-server/pull/76/commits/97d8c4dc8624a679f4ed069649204c02e8938f37 
`ipld-eth-server` accepts chain parameter to pass custom chain config.

**Comment by nikugogoi** [comment]
Getting response now with proper values.

Using JSON RPC methods like getBalance and blockNumber log errors in ipld-eth-server
```
ERRO[2021-08-12T11:34:59+05:30] tx cid retrieval error                       
ERRO[2021-08-12T11:34:59+05:30] ChainId failed with err missing destination name tx_type in *[]eth.TxModel
```

Using eth_call for a contract shows the same errors along with a warning
```
WARN[2021-08-12T11:35:38+05:30] Caller gas above allowance, capping; requested: 9223372036854775807, cap: 1000000000000
```

**Comment by ramilexe** [comment]
As discussed in slack channel:

It appears when you use incompatible versions of statediff-migrations and ipld-eth-server.

[here](https://github.com/vulcanize/statediff-migrations/blob/master/db/migrations/00022_add_tx_type_to_transaction_cids.sql) we added tx_type to transaction_cids table

[here](https://github.com/vulcanize/ipld-eth-server/blob/969da82f6efecd250457344ec725b87b532d564a/pkg/eth/cid_retriever.go#L572)  we do `select * from transaction_cids` and put it to `TxModel` object.

`TxModel` imported from `ipld-eth-indexer` and it is not updated to use tx_type field: https://github.com/vulcanize/ipld-eth-indexer/blob/c365dad5f72ec78e0f881421effc3fff9ae4737c/pkg/eth/models.go#L53-L63

Upgrading dependency to latest `ipld-eth-indexer` is in this PR https://github.com/vulcanize/ipld-eth-server/pull/92

Also, to be able to work with existing version of `ipld-eth-server` please use `statediff-migrations` the same version
as in docker-compose file https://github.com/vulcanize/ipld-eth-server/blob/master/docker-compose.yml#L19

**Comment by ashwinphatak** [comment]
Works on ipld-eth-server master

**Comment by ashwinphatak** [comment]
Reopening as on current master, it shows the following error, though smoke tests pass:

```
WARN [09-23|11:48:37.083] Served eth_call                          conn=127.0.0.1:50906 reqid=92 t=3.312746ms err="eth_call failed without error"

```

**Comment by nikugogoi** [comment]
eth_call working and tested with ipld-eth-server master branch. Commit hash:
https://github.com/vulcanize/ipld-eth-server/tree/0f2b6fd84351aa91fd8aaeab75f7a67a23182c8f
