### ISSUE TITLE
Make eth_calls based on block hash

### ISSUE THREAD

**Issue by ashwinphatak** [vulcanize/uniswap-watcher-ts#279]
Depends on https://github.com/vulcanize/ipld-eth-server/issues/115

**Comment by nikugogoi** [comment]
ethers.js removes the leading zeros in the blockHash when providing it as blockTag in making an eth_call.
For example, when using blockHash `0x050033bd7ab5d7cd4763d00155fd681803692a17014f325f5962243c8c3fd54d`, it is converted to `0x50033bd7ab5d7cd4763d00155fd681803692a17014f325f5962243c8c3fd54d` in the eth_call request body.
